### ISSUE TITLE
Implement EXTTP in CoolProp wrapper

### ISSUE THREAD

**Issue by jowr** [CoolProp/ExternalMedia#1]
Splitting several issues from https://github.com/CoolProp/CoolProp/issues/263.

**Comment by JonWel** [comment]
Some variables have no physical value in the twophase region, however Modelica expect real values in this area.
The solution is to interpolate from the two saturated values (mainly linearly, but one is the inverse of the linear interpolation of the inverse values).

However, When I tested some fluids in the twophase region, I still get some values (not always linear, but they don't simply explode to `Inf` for the whole twophase area).

As I understand, the new code should takes values from `CoolProp` when `phase = 1` and takes the saturated values (from ancillary?) and the quality to compute the regression.

**Comment by JonWel** [comment]
Would changing the compressible part of the `postStateChange` function like below a efficient solution for EXTTP?
(Watch the part with `if ((extend_twophase) && (phase ==2)){`)

``` C++
properties->p = state->p();
properties->T = state->T();
properties->d = state->rhomass();
properties->h = state->hmass();
properties->s = state->smass();
if (state->phase() == CoolProp::iphase_twophase){
    properties->phase = 2;
}
else{
    properties->phase = 1;
}
properties->cv = state->cvmass();
properties->a = state->speed_sound();
if ((state->phase() == CoolProp::iphase_twophase) && state->Q() >= 0 && state->Q() <= twophase_derivsmoothing_xend && twophase_derivsmoothing_xend > 0.0)
{
    // Use the smoothed derivatives between a quality of 0 and twophase_derivsmoothing_xend
    properties->ddhp = state->first_two_phase_deriv_splined(CoolProp::iDmass, CoolProp::iHmass, CoolProp::iP, twophase_derivsmoothing_xend); // [1/kPa -- > 1/Pa]
    properties->ddph = state->first_two_phase_deriv_splined(CoolProp::iDmass, CoolProp::iP, CoolProp::iHmass, twophase_derivsmoothing_xend); // [1/(kJ/kg) -- > 1/(J/kg)]
}
else if ((state->phase() == CoolProp::iphase_twophase) && state->Q() >= 0 && state->Q() <= rho_smoothing_xend && rho_smoothing_xend > 0.0)
{
    // Use the smoothed density between a quality of 0 and rho_smoothing_xend
    properties->ddhp =  state->first_two_phase_deriv_splined(CoolProp::iDmass, CoolProp::iHmass, CoolProp::iP, rho_smoothing_xend);;
    properties->ddph = state->first_two_phase_deriv_splined(CoolProp::iDmass, CoolProp::iP, CoolProp::iHmass, rho_smoothing_xend);;
    properties->d = state->first_two_phase_deriv_splined(CoolProp::iDmass, CoolProp::iDmass, CoolProp::iDmass, rho_smoothing_xend);
}
else
{
    properties->ddhp = state->first_partial_deriv(CoolProp::iDmass, CoolProp::iHmass, CoolProp::iP);
    properties->ddph = state->first_partial_deriv(CoolProp::iDmass, CoolProp::iP, CoolProp::iHmass);
}


if ((extend_twophase) && (properties->phase ==2)){
    // Saturation values Q=0
    double cp_L, kappa_L, beta_L, eta_L, labda_L; 
    state->update(CoolProp::PQ_INPUTS,properties->p,0);

    cp_L = state->cpmass();
    kappa_L = state->isothermal_compressibility();
    beta_L = state->isobaric_expansion_coefficient();
    if (calc_transport)
    {
        eta_L = state->viscosity();
        lambda_L = state->conductivity();
    }

    // Saturation values Q=1
    double cp_V, kappa_V, beta_V, eta_V, labda_V; 
    state->update(CoolProp::PQ_INPUTS,properties->p,1);

    cp_V = state->cpmass();
    kappa_V = state->isothermal_compressibility();
    beta_V = state->isobaric_expansion_coefficient();
    if (calc_transport)
    {
        eta_V = state->viscosity();
        lambda_V = state->conductivity();
    }

    // Interpolation
    properties->cp = interp_linear(state->Q(), cp_L, cp_V);
    properties->kappa = interp_linear(state->Q(), kappa_L, kappa_V);
    properties->beta = interp_linear(state->Q(), beta_L, beta_V);

    if (calc_transport)
    {
        properties->eta = interp_recip(state->Q(), eta_L, eta_V);
        properties->lambda = interp_linear(state->Q(), lambda_L, lambda_V); //[kW/m/K --> W/m/K]
    } else {
        properties->eta    = NAN;
        properties->lambda = NAN;
    }
}
else{
    properties->cp = state->cpmass();
    properties->kappa = state->isothermal_compressibility();
    properties->beta = state->isobaric_expansion_coefficient();

    if (calc_transport)
    {
        properties->eta = state->viscosity();
        properties->lambda = state->conductivity(); //[kW/m/K --> W/m/K]
    } else {
        properties->eta    = NAN;
        properties->lambda = NAN;
    }
}
```

With the two following functions added to the end of the same `coolpropsolver.cpp` file:

``` C++

/// Interpolation routines
double CoolPropSolver::interp_linear(double Q, double valueL, double valueV) {
    return valueL+Q*(valueV-valueL);
}
double CoolPropSolver::interp_recip(double Q, double valueL, double valueV){
    return 1.0 / interp_linear(Q, 1.0/valueL, 1.0/valueV);
}
```

The saturated values are already internally computed inside `CoolProp`, but I don't think we can access them directly at this level.
I know that some updates couple are quicker than the others. Is there a better one to pick than `PQ` for this usage?

**Comment by jowr** [comment]
Looks good so far, just a few questions:
1. You shortcut the transport property definitions by setting them to `NAN`, why do you calculate the other values `cp`, `kappa` and `beta` for the two-phase domain? Could you also set those to `NAN` directly? (In the last `else` branch) 
2. I am not sure I understand the smoothed density part. Does `properties->d = state->first_two_phase_deriv_splined(CoolProp::iDmass, CoolProp::iDmass, CoolProp::iDmass, rho_smoothing_xend);` really work? There are also plenty of `;`...
3. The inaccessible functions you mentioned are `CoolProp::AbstractState::calc_saturated_liquid_keyed_output(parameters key)` and `CoolProp::AbstractState::calc_saturated_vapor_keyed_output(parameters key)`, right? 

Make sure that you are done updating the properties before you change the state of the object to compute the saturation properties. You could also reset the state after processing the EXTTP stuff to make sure it throws an error if the object gets reused without a prior update call.

**Comment by JonWel** [comment]
1. I kept the way it was done with the previous wrapper: https://github.com/modelica/ExternalMedia/blob/master/Projects/Sources/coolpropsolver.cpp#L245 .
   If you want all the 5 properties to be shut down by the `!calc_transport`, that will simplify the code (first check `calc_transport` then `((extend_twophase) && (properties->phase ==2))`.
   Or maybe you advice the value to be `NaN` when  `!((extend_twophase) && (properties->phase ==2))` ? (CoolProp sometimes calculate something in this area).
2. It comes from https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp#L2957 I think it is the way to use it to have the `rho_splined` value. The sad part is that some of the work is done two-three time but the result should be correct.
   You are right for the `;`, I think it comes from a bad copy paste. Corrected: https://github.com/CoolProp/ExternalMedia/commit/7fc029ec034b4f20659e1a27dae977e741ba7e77
3. So instead of:
   
   ``` C++
   state->update(CoolProp::PQ_INPUTS,properties->p,0);
   cp_L = state->cpmass();
   state->update(CoolProp::PQ_INPUTS,properties->p,1);
   cp_V = state->cpmass();
   properties->cp = interp_linear(state->Q(), cp_L, cp_V);
   ```
   
   I would use:
   
   ``` C++
   properties->cp = interp_linear(state->Q(), state->saturated_liquid_keyed_output(CoolProp::iCpmass), state->saturated_vapor_keyed_output(CoolProp::iCpmass));
   ```
   
   That seems in deed better as it does not need two stage changing (quicker and the state remain unchanged). However, I think it is not yet in the tabular backends. Do I ask it as enhancement to `CoolProp`, or do I make one more `if` to do it only when simple `HEOS` backend?

**Comment by jowr** [comment]
1. I think about something as general as 
   
   ``` C++
   } else { // not ((extend_twophase) && (properties->phase ==2))
   if (phase == 2) {
     properties->cp = NAN; 
     properties->kappa = NAN; 
     properties->beta = NAN;
   } else {
     properties->cp = state->cpmass();
     properties->kappa = state->isothermal_compressibility();
     properties->beta = state->isobaric_expansion_coefficient();
   }
   ```
2. If it works, I am happy. I have never used it myself so I am only asking you to make sure that it works as intended.
3. Yes, if you can access `calc_saturated_liquid_keyed_output(parameters key)` and `calc_saturated_vapor_keyed_output`, but I am afraid that they are private functions that are only accessible inside the state object. If so, please just leave things as they were in your original code and make sure to reset the state object to avoid any accidental use afterwards.

**Comment by jowr** [comment]
Oh wait, forget my comment regarding 1. These values might actually be defined for mixtures...

**Comment by JonWel** [comment]
1. /
2. /
3. I corrected the writing for the saturated values:
   
   ``` C++
   properties->cp = interp_linear(state->Q(), state->saturated_liquid_keyed_output(CoolProp::iCpmass), state->saturated_vapor_keyed_output(CoolProp::iCpmass));
   ```
   
   I checked, I can access them (without the `calc` which is for the private function), but they won't work with tabular as not yet implemented.
   Do I fill an issue to add this to the tabular backend or should I manage to only use it with simple `HEOS` backend (not sure it is in the refprop backend neither) and use the original code (with the reset of the state at the end) for the other backends?

**Comment by jowr** [comment]
Thanks for the clarification. Don't mix different state objects, please go for the Q=0|1 update solution for now. Please also file an issue to have the functions implemented in the tabular backends and see if @ibell complains.

**Comment by JonWel** [comment]
@jowr Does https://github.com/CoolProp/ExternalMedia/commit/e6a82c33b91b959a3b0dccb74c8cf137863657ae correspond to what you wanted? (if yes, just close this issue).

**Comment by jowr** [comment]
Yes, it looks good, but now that https://github.com/CoolProp/CoolProp/commit/867b9731f16f33ecfd710df075628f399cdb1ef5 has closed https://github.com/CoolProp/CoolProp/issues/814 , you could also use those functions directly. Sorry for the double work on your side.

**Comment by JonWel** [comment]
Ian has been really fast, the functions are already implemented for the tabular backend (https://github.com/CoolProp/CoolProp/issues/814 ).
Thus I'll do a new patch using theses functions.
Not really a double work, the main work was already done in the original proposal.
