### ISSUE TITLE
rhomolar_critical not implemented for tabular backend

### ISSUE THREAD

**Issue by JonWel** [CoolProp/ExternalMedia#10]
This value is needed for the `CoolPropSolver::setFluidConstants()` function. It is provided by the `HEOS` backend but not by `TTSE` nor `BICUBIC`.

```
Error: calc_rhomolar_critical is not implemented for this backend
```

Tables are thus not usable by `ExternalMedia`.

I opened an issue on `CoolProp` https://github.com/CoolProp/CoolProp/issues/748

**Comment by jowr** [comment]
That is why I handled constants differently earlier... Feel free to introduce a second state object for this kind of values or add the required functionality elsewhere.

**Comment by JonWel** [comment]
https://github.com/CoolProp/CoolProp/pull/749 should fix this.

**Comment by jowr** [comment]
Yes, that is probably the most convenient solution. Thanks.
