### ISSUE TITLE
`if` performance question

### ISSUE THREAD

**Issue by JonWel** [CoolProp/ExternalMedia#12]
At the end of the function `CoolPropSolver::postStateChange`, there is 6 times the checking of the debug level:

``` C++
if (debug_level > 50) std::cout << format("At the end of %s \n","postStateChange");
if (debug_level > 50) std::cout << format("Setting pressure to %f \n",properties->p);
if (debug_level > 50) std::cout << format("Setting temperature to %f \n",properties->T);
if (debug_level > 50) std::cout << format("Setting density to %f \n",properties->d);
if (debug_level > 50) std::cout << format("Setting enthalpy to %f \n",properties->h);
if (debug_level > 50) std::cout << format("Setting entropy to %f \n",properties->s);
```

As it is exactly the same `debug_level` check, wouldn't it be more efficient to make a single `if` and all the `std::cout` in the same bracket or the compilers notice it can optimise it (and there is no point modifying this)?
This is executed each time the state is updated.

This formulations seems more efficient to me:

``` C++
if (debug_level > 50)
{
    std::cout << format("At the end of %s \n","postStateChange");
    std::cout << format("Setting pressure to %f \n",properties->p);
    std::cout << format("Setting temperature to %f \n",properties->T);
    std::cout << format("Setting density to %f \n",properties->d);
    std::cout << format("Setting enthalpy to %f \n",properties->h);
    std::cout << format("Setting entropy to %f \n",properties->s);
}
```

**Comment by jowr** [comment]
Yes, you can do that, but 6 integer comparisons should not matter compared to the rest of the code...

**Comment by JonWel** [comment]
I see, the whole abstract state update and properties calculation takes way more time to execute, making the change quite negligible.

That also means that I should remake the `CoolPropSolver::CoolPropSolver` to makes a bit more check about the tabular backends (to be sure it do not add the information two times). This will allow for more robustness and displaying incoherences (backends can be specified by two ways in the substanceName and one in the libraryName). Checking coherency between the mediumName and the substanceName could also have sense (displaying a warning if not the same).

**Comment by jowr** [comment]
If you would like to learn more about C++ and how to write efficient code, I can only recommend http://www.agner.org/optimize/optimizing_cpp.pdf

**Comment by JonWel** [comment]
Thanks, this seems in deed very instructive and complete.
