### ISSUE TITLE
Incompressibles crash immediately

### ISSUE THREAD

**Issue by jowr** [CoolProp/ExternalMedia#14]
There is almost no output, even in debugging mode.

**Comment by ibell** [comment]
Is this true all the way through CoolProp?

**Comment by jowr** [comment]
Nope, that is why I reported it here.

**Comment by jowr** [comment]
It is related to the composition handling, which is not handled properly in the `coolpropsolver.cpp`.

**Comment by JonWel** [comment]
Yes, there is a problem with Incompressible.
I'm currently having intensive German course, is it right if I start working on this only Sunday?
Thanks for having pointing out the "composition handling".

**Comment by jowr** [comment]
No worries, I am after the bug.

**Comment by JonWel** [comment]
Ok, super.

Why don't we compute the molar mass for incompressible fluids?
And why aren't the derivatives of the density computed?
