### ISSUE TITLE
calc_first_two_phase_deriv_splined missing to tabular backend

### ISSUE THREAD

**Issue by adrett** [CoolProp/ExternalMedia#16]
When I enable the TTSE option e.g. in ExternalMedia.Test.CoolProp.RhoSmoothing it seems that the fluid does not "enter" the two-phase region. Instead the temperature rises until the solver crashes. The same thing happens with and without rho_smoothing.

**Comment by JonWel** [comment]
I think the `calc_first_two_phase_deriv_splined` is missing for the tabular backend. Should be the issue.
