### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by jowr** [CoolProp/ExternalMedia#18]
We should have a CMake file or something similar to create portable projects that help us to debug the cpp files. @JonWel: Can you share your debugging code? I can make the CMake projects.

**Comment by JonWel** [comment]
Here is the file that I usually use: [main.cpp](https://github.com/CoolProp/ExternalMedia/files/213194/main.txt)

This allows to test some of ExternalMedia's functions without the need for Dymola.

**Comment by ibell** [comment]
There are two ways to use your file with cmake that already are useable:
a) Do a build like so:
  `cmake ../.. -DCOOLPROP_MY_MAIN=main.cpp ........`
b) Follow the instructions to add coolprop as a cmake dependency: http://www.coolprop.org/dev/coolprop/wrappers/StaticLibrary/index.html#cmake-integration

Hope that helps

**Comment by jowr** [comment]
I added @JonWel 's file to the tests. Could anyone please test the new workflow?

```
git clone https://github.com/CoolProp/ExternalMedia.git ExternalMedia
cd ExternalMedia/Projects/
BuildLib-CMake.bat
```

**Comment by JonWel** [comment]
Compilation worked for me with VS 2010 en XP.
Also on VS 2015 on W10 64bit (but as I understood, the binaries are made in 32bit by default, did not tried yet to makes them being 64bit).

It seems to give the same results as when I was compiling it before.
I'll take a look to make an example for Ian to work with for the PT issue after eating.

**Comment by jowr** [comment]
OK, have a look at `BuildLib-CMake.bat` to compile for 64bit. I added some comments in that file.

**Comment by JonWel** [comment]
Yes, I saw there was something in that purpose.
If I understand well, this would require to remove the `::` at the beginning of the line:

``` Batch
::set CMake_generator="Visual Studio 14 2015 Win64"
```

**Comment by jowr** [comment]
Yes, but you also have to change

```
:: cmake .. -G "%CMake_generator%"
cmake .. 
```

to 

```
cmake .. -G "%CMake_generator%"
:: cmake .. 
```

to use the settings later on.

**Comment by JonWel** [comment]
That makes sense.

Now, it sees this `CMake_generator`, but for an obscure reason, it can't read correctly the string, stopping at the first space:

``` Batch
CMake Error: Could not create named generator Visual

Generators
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
(...)
```

I even tried copy pasting the line they give in case there would be a typo we don't see, but it still don't want to take the full string on my W10 64bit education virtual machine.

**Comment by jowr** [comment]
Quotation marks?

**Comment by JonWel** [comment]
@jowr Apparently, on my system, it works only without any quotation marks:

``` Batch
set CMake_generator=Visual Studio 14 2015 Win64
```

**Comment by JonWel** [comment]
Now, without theses quotation marks, it also compile fine in 64 bit.
(the issue with PT update is still there, the executable is not in 64bit mode and gives similar results as the 32bit binary)
