### ISSUE TITLE
Call to the AbstractClass

### ISSUE THREAD

**Issue by JonWel** [CoolProp/ExternalMedia#19]
Which is the preferred implementation to call the abstract class:
- static allocation
- dynamic allocation
- [x] shared pointer

With CoolProp 4, it was a dynamic allocation.
With CoolProp 5, the shared pointer are currently in use.

**Comment by ibell** [comment]
Definitely shared pointer.  Because we use abstract base classes, if you
call the factory function you can only deal with pointers.  Functions (and
classes) cab you references to a class derived from AbstractState

**Comment by jowr** [comment]
Yes, shared pointer!
