### ISSUE TITLE
Expose phase function in state?

### ISSUE THREAD

**Issue by jowr** [CoolProp/ExternalMedia#2]
Splitting several issues from https://github.com/CoolProp/CoolProp/issues/263.

> - `CoolProp`'s `isTwoPhase()` function is protected, is there a similar function I can use to replace the old `TwoPhase` property of `CoolProp 4`?

**Comment by JonWel** [comment]
@ibell would it be fine to makes `isTwoPhase()` (or `_phase`) public (instead of protected) in the [AbstractState](https://github.com/CoolProp/CoolProp/blob/master/include/AbstractState.h#L63)?

**Comment by jowr** [comment]
Can't you use the keyed output? `double AbstractState::keyed_output(parameters key)` with `CoolProp.iPhase` as parameter? It simply passes thing on to the `phase()`function.

**Comment by jowr** [comment]
Check the doxygen pages for more info: http://www.coolprop.dreamhosters.com/binaries/sphinx/_static/doxygen/html/namespace_cool_prop.html#a4b49eeb37210a720b188f493955d8364

**Comment by jowr** [comment]
Alternatively, you can use the `phase()` function directly: https://github.com/CoolProp/CoolProp/blob/3c0fc7e0b40e48f6260edb148896fd2bec9b830c/include/AbstractState.h#L424

**Comment by JonWel** [comment]
I did just discovered the path `PhaseSI` => `PropsSI("Phase",...` => `keyed_output`, I also think it should be possible this way.

**Comment by jowr** [comment]
Yes, `state->phase()` should be the fastest...

**Comment by JonWel** [comment]
Isn't this `phase()` function not yet implemented?

``` C++
phases phase(void){ return calc_phase(); };
virtual phases calc_phase(void){ throw NotImplementedError("This backend does not implement calc_phase function"); };
```

https://github.com/CoolProp/CoolProp/blob/master/include/AbstractState.h#L297

However, implementing it may in deed be a good solution.

**Comment by jowr** [comment]
The AbstractState only implements a subset of the functions. Please have a look at the derived classes http://www.coolprop.dreamhosters.com/binaries/sphinx/_static/doxygen/html/class_cool_prop_1_1_abstract_state.html, you should find the implmenetation there.

**Comment by JonWel** [comment]
This should done it (with the `phase()` function):
https://github.com/JonWel/ExternalMedia/commit/9d7b022bda251e3012870e1380704e20aa7aa4b6

Thanks for the learning that even if a function is marked as not implemented in one place, it can be from an other one (I'm still learning `C++`). The basesolver.cpp of ExternalMedia is based on it, but I did not recognised it here.

**Comment by jowr** [comment]
You're welcome. The concept of virtual functions is exactly what you see here. You place a stub in the base class and make sure that all subclasses implement the functionality. This is one way of providing a common interface even though the internal functions of the different implementations do very different things.
