### ISSUE TITLE
Macro max() in cppformat

### ISSUE THREAD

**Issue by JonWel** [CoolProp/ExternalMedia#22]
I get a similar issue than https://github.com/CoolProp/CoolProp/issues/995 after upgrading cppformat.
@jowr where should the modification be done with the cmake file?

``` cmake
set C_OPTS= /DNOMINMAX
```

**Comment by ibell** [comment]
See https://cmake.org/cmake/help/v3.0/command/add_definitions.html

**Comment by JonWel** [comment]
Thanks Ian
