### ISSUE TITLE
Saturation states sL vs. rhoL

### ISSUE THREAD

**Issue by jowr** [CoolProp/ExternalMedia#3]
Splitting several issues from https://github.com/CoolProp/CoolProp/issues/263.

> - When saturation properties are calculated, for two phase fluids, some values are asked specifically for the Liquid or the Vapour phase (`sV`, `sL` ... but also parameters for density or enthalpy) . Where can I find some `CoolProp 5` equivalents?

**Comment by jowr** [comment]
I guess you refer to the ancillary functions. I would recommend not to use the directly because I think you get more consistent results from a state update with `Q=0` or `Q=1`.

**Comment by JonWel** [comment]
Some parts of the old code are as follow:

``` C++
state->update(iT,T,iQ,0); // Quality only matters for pseudo-pure fluids

properties->Tsat = T;
properties->psat = state->pL();
properties->dl = state->rhoL();
properties->dv = state->rhoV();
properties->hl = state->hL();
properties->hv = state->hV();
properties->dTp = state->dTdp_along_sat();

properties->ddldp = state->drhodp_along_sat_liquid();
properties->ddvdp = state->drhodp_along_sat_vapor();
properties->dhldp = state->dhdp_along_sat_liquid();
properties->dhvdp = state->dhdp_along_sat_vapor();

properties->sigma = state->surface_tension(); // Surface tension
properties->sl    = state->sL();    // Specific entropy at bubble line (for pressure ps)
properties->sv    = state->sV();    // Specific entropy at dew line (for pressure ps)
```

For the pressure and the temperature (there is a similar code where it is the pressure that is given), I can simply take the one given by `state->p()` and `state->T()`.

For the others, I separate with two updates (instead of previously one): first with `Q = 0` for Liquid properties, the other with `Q = 1` for vapour properties?

So basically:

``` C++
properties->Tsat = T;

state->update(CoolProp:QT_INPUTS,0,T);
properties->psat = state->p();
properties->dl = state->rhomass();
properties->hl = state->hmass();
// All the other properties with L

state->update(CoolProp:QT_INPUTS,1,T);
properties->dv = state->rhomass();
properties->hv = state->hmass();
// All the other properties with V
```

**Comment by jowr** [comment]
Yes, that is one possibility. Consider specifying the phase to accelerate calculations: 

``` C++
// Ancillary equations - fast but not 100% consistent with the rest
//properties->dl = state->saturation_ancillary(CoolProp::iDmass,0,CoolProp::iT,T);
//properties->dl = state->saturation_ancillary(CoolProp::iDmolar,0,CoolProp::iT,T)/state->molar_mass();

// Full state update - we should do this
// state->specify_phase(CoolProp::iphase_liquid);
state->update(CoolProp::QT_INPUTS,0,T);
properties->dl = state->rhomass();
properties->hl = state->hmass();

// state->specify_phase(CoolProp::iphase_gas);
state->update(CoolProp::QT_INPUTS,1,T);
properties->dv = state->rhomass();
properties->hv = state->hmass();
// state->specify_phase(CoolProp::iphase_not_imposed);
```

Even though this is potentially faster, recommend to **disable** the phase specification until https://github.com/CoolProp/CoolProp/issues/656 is solved. It has proven to yield unexpected results caused by misleading if-else-statements.

Please document that you use the liquid phase pressure as saturation pressure: https://github.com/ibell/coolprop/issues/23

**Comment by jowr** [comment]
Maybe you can add TODO notes all the places where we should use the specified phase. That makes it easier to enable it later.

**Comment by JonWel** [comment]
I did not thought about theses pseudo-pure fluids that do not have a constant temperature when changing phase, I only tried to provide same result as before.
So yes, it would be the bubble point and not the dew point. I'll add this into the doc (in BaseSolver.cpp).

**Comment by jowr** [comment]
I am not sure this is wrong. Please check with the fluidpropsolver and the Modelica code to figure out which quantity sets the state (T or p). I agree that we should use the same property for the state record and for the dew state, but we might have to change the state record to use pressure as well. I am not sure...

**Comment by JonWel** [comment]
The function `setDewState` will in deed give the correct answer given the inputs.
I assumed that the "sat" properties where from the previous "setsat", but it may as well come from the user. There is no point changing this function, you are right.

**Comment by jowr** [comment]
What about these functions? https://github.com/CoolProp/CoolProp/blob/master/include/AbstractState.h#L483-L486:

``` C++
/// Get an output from the saturated liquid state by key
double saturated_liquid_keyed_output(parameters key);
/// Get an output from the saturated vapor state by key
double saturated_vapor_keyed_output(parameters key);
```

**Comment by JonWel** [comment]
I'll use the

```C++
/// Get an output from the saturated liquid state by key
double saturated_liquid_keyed_output(parameters key);
/// Get an output from the saturated vapor state by key
double saturated_vapor_keyed_output(parameters key);
```
to improve the function `setSat_p`. Once done, it should close this issue.

**Comment by JonWel** [comment]
Using:

``` C++
/// Get an output from the saturated liquid state by key
double saturated_liquid_keyed_output(parameters key);
/// Get an output from the saturated vapor state by key
double saturated_vapor_keyed_output(parameters key);
```

to improve the function `setSat_p` may be interesting but the derivatives along the the vapour saturated line would still need a state update.

Theses two functions are the solution to this issue but I see no point using them in `setSat_p` until there would be similar functions for the derivatives.

I will still clear the state at the end of this function to be sure it always set the required state before retrieving the values.

https://github.com/CoolProp/CoolProp/issues/656 is closed, so I'll uncomment the `specify_phase`.

**Comment by adex987** [comment]
How I define for density of dew and bubble?
I am sure density of bubble and saturated liquid densities are different.

**Comment by JonWel** [comment]
They are computed differently, you have:
`dl` for the bubble density.
`dv` for the dew  density.

**Comment by adex987** [comment]
Thank you for the response but didn't work.I am using "CoolPropMATLAB_wrap".
Example:
CoolProp.PropsSI('dl', 'T', 373, 'Q', 0, 'Water'), didn't work but the following works, which is saturated liquid not bubble density.
CoolProp.PropsSI('D', 'T', 373, 'Q', 0, 'Water')

**Comment by JonWel** [comment]
Adex, be careful that this part is about `ExternalMedia`, a wrapper for `Modelica`, not `Matlab`.
The general `CoolProp` is there: https://github.com/CoolProp/CoolProp

What I would suggest you is first to compute the saturation pressure of interest:
``` matlab
presure = CoolProp.PropsSI('P', 'T', 373, 'Q', 0, 'Water')
```
Then you compute the two relevant densities:
``` matlab
dl = CoolProp.PropsSI('D', 'P', presure, 'Q', 0, 'Water')
dv = CoolProp.PropsSI('D', 'P', presure, 'Q', 1, 'Water')
```
