### ISSUE TITLE
Numerical methods

### ISSUE THREAD

**Issue by jowr** [CoolProp/ExternalMedia#4]
Splitting several issues from https://github.com/CoolProp/CoolProp/issues/263. 

What should be reimplemented:
- [x] `calc_transport`
- [x] `enable_TTSE`
- [x] `enable_BICUBIC`
- [x] `extend_twophase` (enable EXTTP)
- [x] `twophase_derivsmoothing_xend`
- [x] `rho_smoothing_xend`
- [x] tabular two phase derivatives
- [x] tabular two phase smoothed derivatives

... and make sure that there is a converter function to make it backwards compatible.

**Comment by jowr** [comment]
Please add more here if there is an option I forgot.

**Comment by JonWel** [comment]
For the `twophase_derivsmoothing_xend`, can we simply replace:

``` C++
properties->ddhp = state->drhodh_constp_smoothed(twophase_derivsmoothing_xend);
```

With:

``` C++
properties->ddhp = state->first_two_phase_deriv_splined(CoolProp::iDmass, CoolProp::iHmass, CoolProp::iP, twophase_derivsmoothing_xend);
```

That may be an easy solution to this parameter.

**Comment by jowr** [comment]
I recommend to start by implementing all options without content. Make the structure and fill in functionality later. This speeds up the process as we can start testing earlier. Please also consider uploading your code so I can help you with reviewing your changes.

**Comment by JonWel** [comment]
So for `rho_smoothed`, I implement a new protected function at the end of the `coolpropsolver.cpp` file that does the same thing than the previous one from `CoolProp 4`.
```C++
void CoolPropSolver::rho_smoothed(rho_smoothing_xend, rho_spline, dsplinedh, dsplinedp){
...
}
```
(This is a check for good practice, it would also be possible to calculate all the necessary in the `postStateChange` function)

**Comment by JonWel** [comment]
For the `calc_transport` option, this is just an 'if' that compute or not the two properties (so not a lot to change between `CoolProp` versions).
The value of the non computed parameters is correctly updated to `4.29497e+009` that should be equal to `0xffffffff` that define `NaN` in the Include.h file.
I think the `calc_transport` is OK.

**Comment by jowr** [comment]
Just an idea: It keeps the old value if you do not remove it, maybe you could some pre-state change thing to flush out old values. It looks like this should be an ExternalMedia issue since the `AbstractState` clears the values, see https://github.com/CoolProp/CoolProp/blob/master/src/AbstractState.cpp#L179

**Comment by JonWel** [comment]
I have it: `setSat_p` is computing theses values.
So I think I should add this `if` to this function to have the expected behaviour.

**Comment by JonWel** [comment]
Ian is working on the tabular backend to correct a [bug](https://github.com/CoolProp/CoolProp/issues/750#issuecomment-125804029). Once done we should be closer to working tables (difficult to know if there will be others one after).

The main remaining thing now is the `EXTTP`, I'll start this this afternoon.

**Comment by JonWel** [comment]
Ian has corrected the bug I spoke in the previous comment.
Now I see that surface tension is not (yet?) implemented in the tabular backend, do I make an `if` to only calculate it if there is no tabular backend or do we implement it in the tabular backend? (I've no idea about the amount of work  needed).

**Comment by ibell** [comment]
We implement it in the tabular backend.  Can you file an issue please?

**Comment by JonWel** [comment]
done: https://github.com/CoolProp/CoolProp/issues/760

**Comment by JonWel** [comment]
`calc_phase`: https://github.com/CoolProp/CoolProp/issues/763

**Comment by jowr** [comment]
Is this solved? All boxes are checked, but I am not sure whether we can close this issue... @JonWel ?

**Comment by JonWel** [comment]
@jowr I added the remaining element we need to solve in the list.
(it has already has two issues opened, so we can also just close this one and just solve the issues)

**Comment by jowr** [comment]
I guess that closing #16 also means that this one is finally done.
